---
title: "Camille"
author: "Camille H. Ross"
date: '2022-06-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tick data

```{r}
# Load libraries
library(tidyverse)

# Read in data
ticks <- readr::read_csv("https://data.ecoforecast.org/targets/ticks/ticks-targets.csv.gz", guess_max = 1e6)
```

## Make a plot

```{r}
# Plot tick data
ggplot2::ggplot(data = ticks, mapping = aes(x = time, y = amblyomma_americanum, color = siteID)) +
  ggplot2::geom_point() +
  ggplot2::scale_colour_viridis_d() +
  theme_bw() +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 18))

```

```{r}
# Plot tick data
ggplot2::ggplot(data = ticks, mapping = aes(x = mmwrWeek, y = amblyomma_americanum)) +
  ggplot2::geom_point() +
  facet_wrap(~siteID) +
  theme_bw() +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 18))

konz <- ticks |> dplyr::filter(siteID == "KONZ")

tick.rf <- randomForest(amblyomma_americanum ~ ., data = konz[1:30,], importance = TRUE,
                        proximity = TRUE)

konz$pred <- predict(tick.rf, konz)

ggplot(data = konz, aes(x = time, y = amblyomma_americanum)) +
  geom_point() +
  geom_line(data = konz[1:30,], aes(x = time, y = pred)) +
  geom_line(data = konz[30:nrow(konz),], aes(x = time, y = pred), color = "red")
```

```{r}
library(rjags)
library(coda)

RandomWalk = "
model{
  
  #### Data Model
  for(t in 1:n){
    y[t] ~ dnorm(x[t],tau_obs)
  }
  
  #### Process Model
  for(t in 2:n){
    x[t] ~ dnorm(x[t-1],tau_add)
  }
  
  #### Priors
  x[1] ~ dnorm(x_ic,tau_ic)
  tau_obs ~ dgamma(a_obs,r_obs)
  tau_add ~ dgamma(a_add,r_add)
}
"

konz <- ticks |> dplyr::filter(siteID == "KONZ") 
konz$amblyomma_americanum[konz$amblyomma_americanum == 0] <- NA
attach(konz)

data <- list(y=log(amblyomma_americanum + 0.001),n = length(amblyomma_americanum),      ## data
             x_ic=log(1000),tau_ic=100, ## initial condition prior
             a_obs=1,r_obs=1,           ## obs error prior
             a_add=1,r_add=1            ## process error prior
             )

j.model   <- jags.model(file = textConnection(RandomWalk),
                        data = data,
                        n.chains = 3)

## burn-in
jags.out   <- coda.samples (model = j.model,
                            variable.names = c("tau_add","tau_obs", "x"),
                            n.iter = 10000)
#plot(jags.out)

#gelman.diag(jags.out)

#BGR <- gelman.plot(jags.out)

time.rng = c(1,length(time))       ## adjust to zoom in and out
out <- as.matrix(jags.out)         ## convert from coda to matrix  
x.cols <- grep("^x",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(exp(out[,x.cols]),2,quantile,c(0.025,0.5,0.975)) ## model was fit on log scale

plot(time,ci[2,],type='n',ylim=range(amblyomma_americanum,na.rm=TRUE),ylab="Flu Index",log='y',xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){ 
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
points(time,amblyomma_americanum,pch="+",cex=0.5)
```


```{r}
daymet <- readr::read_csv("daymetChallengeSites.csv")

ggplot(data = daymet, mapping = aes(x = Date, y = maxTemperature)) +
  geom_point()
```





