---
title: "Jody's code"
author: "Jody Reimer"
date: '2022-06-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(JAGS_HOME="C:/Program Files/JAGS/JAGS-4.3.0") #my rjags needs this for some reason to find it
library(rjags)
```

```{r}
ticks <- readr::read_csv("https://data.ecoforecast.org/targets/ticks/ticks-targets.csv.gz", guess_max = 1e6)
ticks <- ticks[ticks$amblyomma_americanum != 0.0,] # get rid of 0s for now
#ticks <- ticks[ticks$siteID == "KONZ",] #[1] "BLAN" "KONZ" "LENO" "ORNL" "OSBS" "SCBI" "SERC" "TALL" "UKFS"

ticks$time = as.Date(ticks$time)
ticks <- ticks[order(ticks$time),]
fullticks <- ticks
nforecast <- 5
ticks[(nrow(ticks)-nforecast):nrow(ticks),"amblyomma_americanum"] <- NA
y = (ticks$amblyomma_americanum)

```

```{r}
RandomWalk = "
model{
  
  #### Data Model
  for(t in 1:n){
    y[t] ~ dnorm(x[t],tau_obs)
  }
  
  #### Process Model
  for(t in 2:n){
    x[t]~ dnorm(y[t-1],tau_add)
    #x[t]<-max(0,z[t])
  }
  
  #### Priors
  x[1] ~ dnorm(x_ic,tau_ic)
  tau_obs ~ dgamma(a_obs,r_obs)
  tau_add ~ dgamma(a_add,r_add)
}
"
```

```{r}
data <- list(y=y,n=length(y),      ## data
             x_ic=5,tau_ic=100, ## initial condition prior (NEEDS)
             a_obs=1,r_obs=0.00001,           ## obs error prior
             a_add=1,r_add=1000            ## process error prior
             )
```

```{r}
nchain = 3
init <- list()
for(i in 1:nchain){
  y.samp = sample(y,length(y),replace=TRUE)
  init[[i]] <- list(tau_add=1/var(diff(log(y.samp))),  ## initial guess on process precision
                    tau_obs=5/var(log(y.samp)))        ## initial guess on obs precision
}
```

```{r}
j.model   <- jags.model (file = textConnection(RandomWalk),
                             data = data,
                             inits = init,
                             n.chains = 3)
```
First, check convergence by just looking at tau_add and tau_obs
```{r, fig.asp = 1.0}
## burn-in
jags.out   <- coda.samples (model = j.model,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 5000)
plot(jags.out)
```
```{r, fig.asp = 1.0}
## burn-in
jags.out   <- coda.samples (model = j.model,
                            variable.names = c("x","tau_add","tau_obs"),
                                n.iter = 5000)
```

```{r}
time.rng = c(1,length(ticks$time))       ## adjust to zoom in and out
out <- as.matrix(jags.out)         ## convert from coda to matrix  
x.cols <- grep("^x",colnames(out)) ## grab all columns that start with the letter x
#ci <- apply(exp(out[,x.cols]),2,quantile,c(0.025,0.5,0.975)) ## model was fit on log scale
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## model was fit on log scale

#plot(ticks$time,ci[2,],type='n',ylim=range(y,na.rm=TRUE),ylab="Tick density",log='y',xlim=ticks$time[time.rng])
plot(ticks$time,ci[2,],type='n',ylim=range(y,na.rm=TRUE),ylab="Tick density",xlim=ticks$time[time.rng])

## adjust x-axis label to be monthly if zoomed
#if(diff(time.rng) < 100){ 
#  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
#}
ecoforecastR::ciEnvelope(ticks$time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
points(ticks$time,y,pch="+",cex=0.5)
points(fullticks$time[(nrow(fullticks)-nforecast):nrow(fullticks)],fullticks$amblyomma_americanum[(nrow(fullticks)-nforecast):nrow(fullticks)],pch="o",cex=0.5,col="red")
```

